### ISSUE TITLE
Application keeps crashing

### ISSUE THREAD

**Issue by Hund** [bubelov/news#124] opened 2022-01-15 13:02 UTC
I bookmarked an article that I was reading and the application instantly crashed. If I try to start it again it just instantly crashes again.

I'm using version 0.3.2 from F-Droid with the Miniflux backend on my Google Pixel 3a with LineageOS.

**Comment by bubelov** [comment] 2022-01-19 06:51
@Hund can you name that article and the feed?

**Comment by Hund** [comment] 2022-01-19 11:15
> @Hund can you name that article and the feed?

I don't remember what it was, but I tried the first article that popped up when I started over with the client.

This time it was:

https://www.sweclockers.com/artikel/33589-veckans-fraga-ar-nfts-har-for-att-stanna

And the same thing happened now as well. Here's the feed:

https://www.sweclockers.com/feeds/nyheter

**Comment by bubelov** [comment] 2022-01-29 13:28
@Hund just checked this feed and it works fine on my device. Did you add any extra settings for this feed on Miniflux side, like trying to show full article content in the app?

**Comment by Hund** [comment] 2022-01-29 13:41
> @Hund just checked this feed and it works fine on my device. Did you add any extra settings for this feed on Miniflux side, like trying to show full article content in the app?

I did. Fetching the full article is a requirement.

**Comment by bubelov** [comment] 2022-01-29 14:46
@Hund I see. I'll enable it and see what happens. I have a theory that it crashes because of Android limit on DB cursor size (10M). Some websites embed pics directly in HTML and it caused some issues in the past

**Comment by bubelov** [comment] 2022-02-09 05:17
@Hund still can't reproduce your issue, unfortunately, but there is a way to find out what's wrong. I added a global crash handler to debug builds, so you can grab the latest build and reproduce it there:

https://github.com/bubelov/news/releases/tag/preview

It won't interfere with your original app, they have separate namespaces. This handler just asks you to share the stack trace if it detects a crash. I'm planning to improve the UI and test it a bit more before rolling it out to F-Droid builds, but stack trace sharing should be helpful for issues like this one

**Comment by Hund** [comment] 2022-02-12 05:31
This is what I got:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonElement com.google.gson.JsonObject.get(java.lang.String)' on a null object reference
	at api.miniflux.MinifluxApiBuilder.build$lambda-1(MinifluxApiBuilder.kt:34)
	at api.miniflux.MinifluxApiBuilder.$r8$lambda$7Q_9JMVsIWmDiosKbtM05aB3Xhc(Unknown Source:0)
	at api.miniflux.MinifluxApiBuilder$$ExternalSyntheticLambda1.intercept(Unknown Source:0)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at api.miniflux.MinifluxApiBuilder.build$lambda-0(MinifluxApiBuilder.kt:26)
	at api.miniflux.MinifluxApiBuilder.$r8$lambda$NiOioOlPrTH0WaRSbZlQbu2vzPo(Unknown Source:0)
	at api.miniflux.MinifluxApiBuilder$$ExternalSyntheticLambda0.intercept(Unknown Source:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by Hund** [comment] 2022-02-13 08:20
Here you go.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.gson.JsonElement com.google.gson.JsonObject.get(java.lang.String)' on a null object reference
	at api.miniflux.MinifluxApiBuilder.build$lambda-1(MinifluxApiBuilder.kt:35)
	at api.miniflux.MinifluxApiBuilder.$r8$lambda$7Q_9JMVsIWmDiosKbtM05aB3Xhc(Unknown Source:0)
	at api.miniflux.MinifluxApiBuilder$$ExternalSyntheticLambda1.intercept(Unknown Source:0)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at api.miniflux.MinifluxApiBuilder.build$lambda-0(MinifluxApiBuilder.kt:26)
	at api.miniflux.MinifluxApiBuilder.$r8$lambda$NiOioOlPrTH0WaRSbZlQbu2vzPo(Unknown Source:0)
	at api.miniflux.MinifluxApiBuilder$$ExternalSyntheticLambda0.intercept(Unknown Source:4)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
```

**Comment by bubelov** [comment] 2022-02-13 10:07
@Hund whoops, I added check for the wrong state so the error is still uncaught. Can you please try again, it should catch it now

**Comment by Hund** [comment] 2022-02-17 06:52
> @Hund whoops, I added check for the wrong state so the error is still uncaught. Can you please try again, it should catch it now

I'm sorry, but it works with that version. I can't give you any logs.

**Comment by bubelov** [comment] 2022-02-17 10:54
@Hund interesting. Did you change anything server-side? It was probably a server issue. Anyway, closing this issue since it's no longer reproducable. Feel free to re-open with new logs if it fails again

**Closed by bubelov** 2022-02-17 10:54 UTC
Labels: bug

**Comment by Hund** [comment] 2022-02-17 10:59
> @Hund interesting. Did you change anything server-side? It was probably a server issue. Anyway, closing this issue since it's no longer reproducable. Feel free to re-open with new logs if it fails again

I'm using the plaid hosting, so I have no idea if anything has changed. :)
