### ISSUE TITLE
Full article view

### ISSUE THREAD

**Issue by IndomitableAlbus** [bubelov/news#190] opened 2022-12-28 20:43 UTC
Hi Dev. 
Probably the nicest looking rss feed reader I've used yet. 
The UI is modern and beautiful. 
Adding feeds is simple and the retrieved content including preview images perfect. 
Please can I submit a feature request to include downloading the full article to read in the app as Feedly and inoreader do instead of at present going to the original sources website. 
That's it, thanks.

**Comment by bubelov** [comment] 2023-01-05 11:01
Dupe of https://github.com/bubelov/news/issues/133

**Closed by bubelov** 2023-01-05 11:01 UTC
Labels: enhancement
