### ISSUE TITLE
Error while importing OPML file

### ISSUE THREAD

**Issue by shuvashish76** [bubelov/news#86] opened 2021-10-15 06:04 UTC
![image](https://user-images.githubusercontent.com/48226312/137439991-9754b998-c607-4c30-a0ab-63d89312937c.png)

`.opml` file exported from [NewsBlur](https://github.com/samuelclay/NewsBlur)
Mode: Standalone mode (Beta)
App version: 0.2.9 (15) [F-Droid]

**Comment by bubelov** [comment] 2021-10-15 08:22
@shuvashish76 it will work in the next release. For now, you can grab the latest nightly APK from GitHub CI: https://github.com/bubelov/news/actions/runs/1341638053

**Comment by bubelov** [comment] 2021-11-23 04:46
Fixed in v0.3.1

**Comment by sivaraam** [comment] 2022-01-01 07:28
Strangely. I'm still observing precisely the same error when trying to import an OPML file exported from Feeder. I use v0.3.2 of the app.

**Comment by bubelov** [comment] 2022-01-03 07:47
@sivaraam are you sure it fails on parsing the same field (`type`)? Some feed readers are known to output invalid OPML with some mandatory files missing

**Comment by sivaraam** [comment] 2022-01-04 17:36
> @sivaraam are you sure it fails on parsing the same field (`type`)?

Yeah. I see a very similar error message. See screenshot of error.

<details>
  <summary>Screenshot of error</summary>

![Screenshot_20220104-230339](https://user-images.githubusercontent.com/12448084/148100229-048d64f0-3074-4beb-a2fd-7ea3bbdcc3e8.jpg)


</details>

>  Some feed readers are known to output invalid OPML with some mandatory files missing

Oh. I'm not sure about. I exported the OPML file from Feeder [[repo link](https://gitlab.com/spacecowboy/Feeder)]. Are you aware of any issues with OPML exported from it?

**Comment by bubelov** [comment] 2022-01-21 06:03
@sivaraam can you provide that OPML file? It will allow me to reproduce your issue and see what's wrong. You can probably cut most of your feeds, just a few should be enough

**Comment by sivaraam** [comment] 2022-01-27 18:32
> @sivaraam can you provide that OPML file? It will allow me to reproduce your issue and see what's wrong. You can probably cut most of your feeds, just a few should be enough

Hi! Here's a trimmed OPML export of my feeds that still fails to import in the app:

https://drive.google.com/file/d/1LJm6DtYJZK9U3vdA0SRRpk1F8DAWYT3Q/view?usp=sharing 

PS:  Couldn't upload it to GitHub directly, hence the drive link.

**Comment by locness3** [comment] 2022-01-28 22:22
Hi! I'm also facing this issue with an OPML file exported from [Inoreader](https://inoreader.com).
News version 0.3.2 from F-Droid as well. 
[Here's the file](https://locness.duckdns.org/drop/f.php?h=35J-ec6e&d=1), I did manually remove a few feeds.

**Comment by bubelov** [comment] 2022-01-29 10:35
@sivaraam ah, I see. This file has a nested structure, which is allowed by spec:

> An <outline> may contain zero or more <outline> sub-elements

My parser doesn't support nested outlines, but supporting it shouldn't be hard. I'll include it in the next release which I'm planning to publish in a few days

**Comment by bubelov** [comment] 2022-01-29 10:41
@locness3 your OPML also seems to be nested, so the post above applies to your issue too

**Comment by bubelov** [comment] 2022-01-29 13:12
Fixed in https://github.com/bubelov/news/commit/1278ba9f1a0340432c661bdd1c36868f72809a87

**Closed by bubelov** 2022-01-29 13:12 UTC

**Comment by locness3** [comment] 2022-01-29 22:52
Thank you so much!
